# Generated by Django 3.0.4 on 2020-03-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('codigo_postal', models.IntegerField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
